In [87]:

import json


# way_point_1_path = "/home/hanse/manipulator_Deep/IoT-repo-3/src/ai_manipulation/ai_manipulation/script/way_point_1.json"
# way_point_2_path = "/home/hanse/manipulator_Deep/IoT-repo-3/src/ai_manipulation/ai_manipulation/script/way_point_2.json"
way_point_11_path = "/home/hanse/git_ws/final_project/src/ai_manipulation/ai_manipulation/script/Down_list.json"
way_point_22_path = "/home/hanse/git_ws/final_project/src/ai_manipulation/ai_manipulation/script/Up_list.json"




    # Read JSON
# with open(way_point_11_path, 'r') as json_file:
#     way_point_1 = json.load(json_file)
with open(way_point_22_path, 'r') as json_file:
    way_point_1 = json.load(json_file)

print(way_point_1)

[[-0.9111846089363098, 0.5414952039718628, -0.725572943687439, 1.7794177532196045, -0.8697671294212341, -1.101398229598999], [-0.725572943687439, 0.9081166386604309, -1.3867186307907104, 2.0509324073791504, -0.6488738656044006, -1.0998642444610596], [-0.7455146908760071, 0.15800002217292786, 0.00920388475060463, 1.466485619544983, -0.7347767949104309, -1.0998642444610596], [-0.6197282671928406, 0.4187767803668976, -0.40957286953926086, 1.512505054473877, -0.5813787579536438, -1.0983302593231201], [-0.45712628960609436, -0.03988350182771683, 0.15033012628555298, 1.5370488166809082, -0.46019425988197327, -1.0998642444610596], [-0.37275734543800354, 0.36508744955062866, -0.4448544383049011, 1.6659032106399536, -0.34821364283561707, -1.0998642444610596], [-0.15186409652233124, -0.08130098134279251, 0.18867963552474976, 1.5523885488510132, -0.15186409652233124, -1.0998642444610596], [-0.15033012628555298, 0.37889325618743896, -0.37275734543800354, 1.5984079837799072, -0.15186409652233124, -1.0998642444610596], [0.019941750913858414, -0.06596117466688156, 0.16106799244880676, 1.4894953966140747, 0.03681553900241852, -1.101398229598999], [-0.006135923322290182, 0.3328738510608673, -0.323669970035553, 1.607611894607544, 0.0, -1.101398229598999], [0.9111846089363098, 0.5414952039718628, -0.725572943687439, 1.7794177532196045, -0.8697671294212341, -1.101398229598999], [0.725572943687439, 0.9081166386604309, -1.3867186307907104, 2.0509324073791504, -0.6488738656044006, -1.0998642444610596], [0.7455146908760071, 0.15800002217292786, 0.00920388475060463, 1.466485619544983, -0.7347767949104309, -1.0998642444610596], [0.6197282671928406, 0.4187767803668976, -0.40957286953926086, 1.512505054473877, -0.5813787579536438, -1.0983302593231201], [0.45712628960609436, -0.03988350182771683, 0.15033012628555298, 1.5370488166809082, -0.46019425988197327, -1.0998642444610596], [0.37275734543800354, 0.36508744955062866, -0.4448544383049011, 1.6659032106399536, -0.34821364283561707, -1.0998642444610596], [0.15186409652233124, -0.08130098134279251, 0.18867963552474976, 1.5523885488510132, -0.15186409652233124, -1.0998642444610596], [0.15033012628555298, 0.37889325618743896, -0.37275734543800354, 1.5984079837799072, -0.15186409652233124, -1.0998642444610596]]

In [88]:
import pandas as pd

In [89]:
way_point_1 = pd.DataFrame(way_point_1)

In [90]:
way_point_1

           0         1         2         3         4         5
0  -0.911185  0.541495 -0.725573  1.779418 -0.869767 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932 -0.648874 -1.099864
2  -0.745515  0.158000  0.009204  1.466486 -0.734777 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505 -0.581379 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049 -0.460194 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903 -0.348214 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389 -0.151864 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408 -0.151864 -1.099864
8   0.019942 -0.065961  0.161068  1.489495  0.036816 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612  0.000000 -1.101398
10  0.911185  0.541495 -0.725573  1.779418 -0.869767 -1.101398
11  0.725573  0.908117 -1.386719  2.050932 -0.648874 -1.099864
12  0.745515  0.158000  0.009204  1.466486 -0.734777 -1.099864
13  0.619728  0.418777 -0.409573  1.512505 -0.581379 -1.098330
14  0.457126 -0.039884  0.150330  1.537049 -0.460194 -1.099864
15  0.372757  0.365087 -0.444854  1.665903 -0.348214 -1.099864
16  0.151864 -0.081301  0.188680  1.552389 -0.151864 -1.099864
17  0.150330  0.378893 -0.372757  1.598408 -0.151864 -1.099864

In [91]:
way_point_1[4] = -1.6

In [92]:
way_point_2=way_point_1.copy() # -1.1
way_point_3=way_point_1.copy() # -.6
way_point_4=way_point_1.copy() # 0.0
way_point_5=way_point_1.copy() # .5
way_point_6=way_point_1.copy() # 1.0
way_point_7=way_point_1.copy() # 1.6

In [93]:
way_point_1

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418 -1.6 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932 -1.6 -1.099864
2  -0.745515  0.158000  0.009204  1.466486 -1.6 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505 -1.6 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049 -1.6 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903 -1.6 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389 -1.6 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408 -1.6 -1.099864
8   0.019942 -0.065961  0.161068  1.489495 -1.6 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612 -1.6 -1.101398
10  0.911185  0.541495 -0.725573  1.779418 -1.6 -1.101398
11  0.725573  0.908117 -1.386719  2.050932 -1.6 -1.099864
12  0.745515  0.158000  0.009204  1.466486 -1.6 -1.099864
13  0.619728  0.418777 -0.409573  1.512505 -1.6 -1.098330
14  0.457126 -0.039884  0.150330  1.537049 -1.6 -1.099864
15  0.372757  0.365087 -0.444854  1.665903 -1.6 -1.099864
16  0.151864 -0.081301  0.188680  1.552389 -1.6 -1.099864
17  0.150330  0.378893 -0.372757  1.598408 -1.6 -1.099864

In [94]:
way_point_2[4] = -1.1
way_point_3[4] = -0.6
way_point_4[4] = 0.0
way_point_5[4] = 0.5
way_point_6[4] = 1.0
way_point_7[4] = 1.6

In [95]:
way_point_7

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418  1.6 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932  1.6 -1.099864
2  -0.745515  0.158000  0.009204  1.466486  1.6 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505  1.6 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049  1.6 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903  1.6 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389  1.6 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408  1.6 -1.099864
8   0.019942 -0.065961  0.161068  1.489495  1.6 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612  1.6 -1.101398
10  0.911185  0.541495 -0.725573  1.779418  1.6 -1.101398
11  0.725573  0.908117 -1.386719  2.050932  1.6 -1.099864
12  0.745515  0.158000  0.009204  1.466486  1.6 -1.099864
13  0.619728  0.418777 -0.409573  1.512505  1.6 -1.098330
14  0.457126 -0.039884  0.150330  1.537049  1.6 -1.099864
15  0.372757  0.365087 -0.444854  1.665903  1.6 -1.099864
16  0.151864 -0.081301  0.188680  1.552389  1.6 -1.099864
17  0.150330  0.378893 -0.372757  1.598408  1.6 -1.099864

In [96]:
way_point_6

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418  1.0 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932  1.0 -1.099864
2  -0.745515  0.158000  0.009204  1.466486  1.0 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505  1.0 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049  1.0 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903  1.0 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389  1.0 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408  1.0 -1.099864
8   0.019942 -0.065961  0.161068  1.489495  1.0 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612  1.0 -1.101398
10  0.911185  0.541495 -0.725573  1.779418  1.0 -1.101398
11  0.725573  0.908117 -1.386719  2.050932  1.0 -1.099864
12  0.745515  0.158000  0.009204  1.466486  1.0 -1.099864
13  0.619728  0.418777 -0.409573  1.512505  1.0 -1.098330
14  0.457126 -0.039884  0.150330  1.537049  1.0 -1.099864
15  0.372757  0.365087 -0.444854  1.665903  1.0 -1.099864
16  0.151864 -0.081301  0.188680  1.552389  1.0 -1.099864
17  0.150330  0.378893 -0.372757  1.598408  1.0 -1.099864

In [97]:
way_point_5

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418  0.5 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932  0.5 -1.099864
2  -0.745515  0.158000  0.009204  1.466486  0.5 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505  0.5 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049  0.5 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903  0.5 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389  0.5 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408  0.5 -1.099864
8   0.019942 -0.065961  0.161068  1.489495  0.5 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612  0.5 -1.101398
10  0.911185  0.541495 -0.725573  1.779418  0.5 -1.101398
11  0.725573  0.908117 -1.386719  2.050932  0.5 -1.099864
12  0.745515  0.158000  0.009204  1.466486  0.5 -1.099864
13  0.619728  0.418777 -0.409573  1.512505  0.5 -1.098330
14  0.457126 -0.039884  0.150330  1.537049  0.5 -1.099864
15  0.372757  0.365087 -0.444854  1.665903  0.5 -1.099864
16  0.151864 -0.081301  0.188680  1.552389  0.5 -1.099864
17  0.150330  0.378893 -0.372757  1.598408  0.5 -1.099864

In [98]:
way_point_4

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418  0.0 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932  0.0 -1.099864
2  -0.745515  0.158000  0.009204  1.466486  0.0 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505  0.0 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049  0.0 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903  0.0 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389  0.0 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408  0.0 -1.099864
8   0.019942 -0.065961  0.161068  1.489495  0.0 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612  0.0 -1.101398
10  0.911185  0.541495 -0.725573  1.779418  0.0 -1.101398
11  0.725573  0.908117 -1.386719  2.050932  0.0 -1.099864
12  0.745515  0.158000  0.009204  1.466486  0.0 -1.099864
13  0.619728  0.418777 -0.409573  1.512505  0.0 -1.098330
14  0.457126 -0.039884  0.150330  1.537049  0.0 -1.099864
15  0.372757  0.365087 -0.444854  1.665903  0.0 -1.099864
16  0.151864 -0.081301  0.188680  1.552389  0.0 -1.099864
17  0.150330  0.378893 -0.372757  1.598408  0.0 -1.099864

In [99]:
way_point_3

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418 -0.6 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932 -0.6 -1.099864
2  -0.745515  0.158000  0.009204  1.466486 -0.6 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505 -0.6 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049 -0.6 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903 -0.6 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389 -0.6 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408 -0.6 -1.099864
8   0.019942 -0.065961  0.161068  1.489495 -0.6 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612 -0.6 -1.101398
10  0.911185  0.541495 -0.725573  1.779418 -0.6 -1.101398
11  0.725573  0.908117 -1.386719  2.050932 -0.6 -1.099864
12  0.745515  0.158000  0.009204  1.466486 -0.6 -1.099864
13  0.619728  0.418777 -0.409573  1.512505 -0.6 -1.098330
14  0.457126 -0.039884  0.150330  1.537049 -0.6 -1.099864
15  0.372757  0.365087 -0.444854  1.665903 -0.6 -1.099864
16  0.151864 -0.081301  0.188680  1.552389 -0.6 -1.099864
17  0.150330  0.378893 -0.372757  1.598408 -0.6 -1.099864

In [100]:
way_point_2

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418 -1.1 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932 -1.1 -1.099864
2  -0.745515  0.158000  0.009204  1.466486 -1.1 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505 -1.1 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049 -1.1 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903 -1.1 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389 -1.1 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408 -1.1 -1.099864
8   0.019942 -0.065961  0.161068  1.489495 -1.1 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612 -1.1 -1.101398
10  0.911185  0.541495 -0.725573  1.779418 -1.1 -1.101398
11  0.725573  0.908117 -1.386719  2.050932 -1.1 -1.099864
12  0.745515  0.158000  0.009204  1.466486 -1.1 -1.099864
13  0.619728  0.418777 -0.409573  1.512505 -1.1 -1.098330
14  0.457126 -0.039884  0.150330  1.537049 -1.1 -1.099864
15  0.372757  0.365087 -0.444854  1.665903 -1.1 -1.099864
16  0.151864 -0.081301  0.188680  1.552389 -1.1 -1.099864
17  0.150330  0.378893 -0.372757  1.598408 -1.1 -1.099864

In [101]:
way_point_1

           0         1         2         3    4         5
0  -0.911185  0.541495 -0.725573  1.779418 -1.6 -1.101398
1  -0.725573  0.908117 -1.386719  2.050932 -1.6 -1.099864
2  -0.745515  0.158000  0.009204  1.466486 -1.6 -1.099864
3  -0.619728  0.418777 -0.409573  1.512505 -1.6 -1.098330
4  -0.457126 -0.039884  0.150330  1.537049 -1.6 -1.099864
5  -0.372757  0.365087 -0.444854  1.665903 -1.6 -1.099864
6  -0.151864 -0.081301  0.188680  1.552389 -1.6 -1.099864
7  -0.150330  0.378893 -0.372757  1.598408 -1.6 -1.099864
8   0.019942 -0.065961  0.161068  1.489495 -1.6 -1.101398
9  -0.006136  0.332874 -0.323670  1.607612 -1.6 -1.101398
10  0.911185  0.541495 -0.725573  1.779418 -1.6 -1.101398
11  0.725573  0.908117 -1.386719  2.050932 -1.6 -1.099864
12  0.745515  0.158000  0.009204  1.466486 -1.6 -1.099864
13  0.619728  0.418777 -0.409573  1.512505 -1.6 -1.098330
14  0.457126 -0.039884  0.150330  1.537049 -1.6 -1.099864
15  0.372757  0.365087 -0.444854  1.665903 -1.6 -1.099864
16  0.151864 -0.081301  0.188680  1.552389 -1.6 -1.099864
17  0.150330  0.378893 -0.372757  1.598408 -1.6 -1.099864

In [102]:
import pandas as pd

# 7개의 10x10 데이터 프레임을 생성하는 예제
data_frames = [way_point_1,
               way_point_2,
               way_point_3,
               way_point_4,
               way_point_5,
               way_point_6,
               way_point_7]

# 빈 데이터 프레임 생성
result = [0,0,0,0,0]

# 각 데이터 프레임의 각 행을 이어붙이기
result = pd.concat([df.iloc[i:i+1] for df in data_frames for i in range(18)])


result.reset_index(drop=True, inplace=True)
# 결과 출력
print(result)
result.to_json('way_point_2.json', orient='split', index=False)

            0         1         2         3    4         5
0   -0.911185  0.541495 -0.725573  1.779418 -1.6 -1.101398
1   -0.725573  0.908117 -1.386719  2.050932 -1.6 -1.099864
2   -0.745515  0.158000  0.009204  1.466486 -1.6 -1.099864
3   -0.619728  0.418777 -0.409573  1.512505 -1.6 -1.098330
4   -0.457126 -0.039884  0.150330  1.537049 -1.6 -1.099864
..        ...       ...       ...       ...  ...       ...
121  0.619728  0.418777 -0.409573  1.512505  1.6 -1.098330
122  0.457126 -0.039884  0.150330  1.537049  1.6 -1.099864
123  0.372757  0.365087 -0.444854  1.665903  1.6 -1.099864
124  0.151864 -0.081301  0.188680  1.552389  1.6 -1.099864
125  0.150330  0.378893 -0.372757  1.598408  1.6 -1.099864

[126 rows x 6 columns]